/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'seo' : null } |
  { 'web_design' : null } |
  { 'web_development' : null } |
  { 'ecommerce' : null };
export interface ContactFormSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'completionYear' : bigint,
  'clientName' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'projectUrl' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'features' : Array<string>,
  'displayOrder' : bigint,
  'description' : string,
  'iconName' : string,
}
export interface SiteSettings {
  'tagline' : string,
  'twitterUrl' : string,
  'instagramUrl' : string,
  'email' : string,
  'whatsappNumber' : string,
  'address' : string,
  'companyName' : string,
  'phone' : string,
  'facebookUrl' : string,
  'linkedinUrl' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPortfolioItem' : ActorMethod<
    [string, string, Category, string, string, string, bigint],
    undefined
  >,
  'createService' : ActorMethod<
    [string, string, Array<string>, string, bigint],
    undefined
  >,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactFormSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getSiteSettings' : ActorMethod<[], [] | [SiteSettings]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updatePortfolioItem' : ActorMethod<
    [bigint, string, string, Category, string, string, string, bigint],
    undefined
  >,
  'updateService' : ActorMethod<
    [bigint, string, string, Array<string>, string, bigint],
    undefined
  >,
  'updateSiteSettings' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];